routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::group(['namespace' => 'Front' ,
             'prefix' =>'{locale}' ,
             'where' => ['locale' =>'[a-zA-Z]{2}'],

        ], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/about', 'HomeController@about');
    Route::get('/manufacturing', 'HomeController@manufacturing');
    Route::get('/contactUs', 'HomeController@contactUs');
    Route::get('/product', 'HomeController@product');
    Route::get('/service', 'HomeController@service');
    Route::get('/jobs', 'HomeController@job');
    Route::get('/register_form', 'HomeController@register');

    Auth::routes();

    Route::get('locale/{locale}', function ($locale){
        Session::put('locale', $locale);
        return redirect()->back();
    });

});
*/
Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/about', 'HomeController@about');
    Route::get('/manufacturing', 'HomeController@manufacturing');
    Route::get('/contactUs', 'HomeController@contactUs');
    Route::get('/product', 'HomeController@product');
    Route::get('/service', 'HomeController@service');
    Route::get('/jobs', 'HomeController@job');
    Route::get('/charts', 'HomeController@charts');
    Route::get('/capitals', 'HomeController@capital');

    Route::get('/register_form', 'HomeController@register');


    // Route::get('contact-us', 'ContactController@contactUs');
    // Route::post('contact-us', 'ContactController@contactUsPost')->name('contactus.store');

    Route::get('locale/{locale}', function ($locale){
        Session::put('locale', $locale);
        return redirect()->back();
    });

});
Auth::routes();
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index');
    Route::resource('/sliders', 'SliderController');
    Route::resource('/services', 'ServiceController');
    Route::resource('/portfolios', 'PortfolioController');
    Route::resource('/teams', 'TeamController');
    Route::resource('/testimonials', 'TestimonialController');
    Route::resource('/reports', 'ReportController');
    Route::resource('/abouts', 'AboutController');
    Route::resource('/statistics', 'StatisticController');
    Route::resource('/advisors', 'AdvisorController');
    Route::resource('/chooses', 'ChooseController');
    Route::resource('/products', 'ProductController');
    Route::resource('/manufacturing', 'ManufacturingController');
    Route::resource('/jobs', 'JobController');
    Route::resource('/charts', 'OrganizationChartController');
    Route::resource('/capitals', 'CapitalController');


});
Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/charts/create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="container">
        <h3 class="jumbotron"> Create New charts</h3>
            <form method="POST" action="{{route('charts.store')}}" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="input-group" >
                    <label>Arabic Chart</label>
                    <input type="file" name="ar_chart" class="form-control">
                    @error('ar_chart')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="input-group" >
                    <label>English Chart</label>
                    <input type="file" name="en_chart" class="form-control">
                    @error('en_chart')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="input-group" >
                    <label>French Chart</label>
                    <input type="file" name="fr_chart" class="form-control">
                    @error('fr_chart')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            <button type="submit" class="btn btn-primary" style="margin-top:10px">Upload</button>
        </form>
    </div>
@endsection

resources/views/admin/charts/edit.blade.php
@extends('admin.layouts.app')
@section('content')
<section class="content">
    <div class="row">
          <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Quick Example</h3>
                </div>
              <!-- /.box-header -->
              <!-- form start -->
                <form  method="post" action="{{route('charts.update' , $charts->id )}}" class="form" enctype="multipart/form-data">
                        {{csrf_field()}}
                        <input type="hidden" name="_method" value="put">
                    <div class="box-body">
                        <div class="input-group control-group increment" >
                            <input type="file" name="ar_chart" class="form-control">
                            <img src = " {{asset('/' . $charts->ar_chart )}}" height="200px" width="200px" >
                            @error('ar_chart')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="input-group control-group increment" >
                            <input type="file" name="en_chart" class="form-control">
                            <img src = " {{asset('/' . $charts->en_chart )}}" height="200px" width="200px" >
                            @error('en_chart')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="input-group control-group increment" >
                            <input type="file" name="fr_chart" class="form-control">
                            <img src = " {{asset('/' . $charts->fr_chart )}}" height="200px" width="200px" >
                            @error('fr_chart')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </div>
                </form>
            </div>
            <!-- /.box -->
        </div>
          <!--/.col (right) -->
    </div>
        <!-- /.row -->
</section>

@endsection

resources/views/admin/charts/index.blade.php
@extends('admin.layouts.app')
@section('content')

<section class="content">
        <a href="{{ route('charts.create') }}" class="btn btn-primary text-capitalize "> add new </a>
            <div class="row">
              <div class="col-md-12">
                <div class="box">
                  <div class="box-header with-border">
                    <h3 class="box-title">chart </h3>
                  </div>
                  <!-- /.box-header -->
                  <div class="box-body">
                    <table class="table table-bordered">
                      <tr>
                        <th style="width: 10px">#</th>
                        <th>Arabic Chart</th>
                        <th>English Chart</th>
                        <th>Freach Chart</th>
                        <th style="width: 100px">actions</th>
                      </tr>
                    @foreach ($charts as $chart)
                        <tr>
                            <td>{{$chart->id}}</td>
                            <td> <img src="{{ asset('/'.$chart->ar_chart) }}" height="100px" width="100px" alt="">
                            <td> <img src="{{ asset('/'.$chart->en_chart) }}" height="100px" width="100px" alt="">
                            <td> <img src="{{ asset('/'.$chart->fr_chart) }}" height="100px" width="100px" alt="">
                            <td>
                                <form method="post" action="{{route('charts.destroy', $chart->id)}}">
                                    <span>
                                        <a href="{{ route('charts.edit', $chart->id) }}"><i class="fa fa-pencil btn btn-primary"> </i></a>
                                    </span>
                                        {{csrf_field()}}
                                        <input type="hidden" name="_method" value="DELETE" />
                                        <div class="btn-group">
                                            <button  onclick="return confirm(' هل انت متاكد ؟؟')" class="fa fa-trash btn btn-danger" type="submit"></button>
                                        </div>
                                </form>
                            </td>
                        </tr>
                        @endforeach

                    </table>
                  </div>
                  <!-- /.box-body -->


              </div>

            </div>

          </section>
          <!-- /.content -->

@endsection