routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::group(['namespace' => 'Front' ,
             'prefix' =>'{locale}' ,
             'where' => ['locale' =>'[a-zA-Z]{2}'],

        ], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/about', 'HomeController@about');
    Route::get('/manufacturing', 'HomeController@manufacturing');
    Route::get('/contactUs', 'HomeController@contactUs');
    Route::get('/product', 'HomeController@product');
    Route::get('/service', 'HomeController@service');
    Route::get('/jobs', 'HomeController@job');
    Route::get('/register_form', 'HomeController@register');

    Auth::routes();

    Route::get('locale/{locale}', function ($locale){
        Session::put('locale', $locale);
        return redirect()->back();
    });

});
*/
Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/about', 'HomeController@about');
    Route::get('/manufacturing', 'HomeController@manufacturing');
    Route::get('/contactUs', 'HomeController@contactUs');
    Route::get('/product', 'HomeController@product');
    Route::get('/service', 'HomeController@service');
    Route::get('/jobs', 'HomeController@job');
    Route::get('/charts', 'HomeController@charts');
    Route::get('/capitals', 'HomeController@capital');

    Route::get('/register_form', 'HomeController@register');


    // Route::get('contact-us', 'ContactController@contactUs');
    // Route::post('contact-us', 'ContactController@contactUsPost')->name('contactus.store');

    Route::get('locale/{locale}', function ($locale){
        Session::put('locale', $locale);
        return redirect()->back();
    });

});
Auth::routes();
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index');
    Route::resource('/sliders', 'SliderController');
    Route::resource('/services', 'ServiceController');
    Route::resource('/portfolios', 'PortfolioController');
    Route::resource('/teams', 'TeamController');
    Route::resource('/testimonials', 'TestimonialController');
    Route::resource('/reports', 'ReportController');
    Route::resource('/abouts', 'AboutController');
    Route::resource('/statistics', 'StatisticController');
    Route::resource('/advisors', 'AdvisorController');
    Route::resource('/chooses', 'ChooseController');
    Route::resource('/products', 'ProductController');
    Route::resource('/manufacturing', 'ManufacturingController');
    Route::resource('/jobs', 'JobController');
    Route::resource('/charts', 'OrganizationChartController');
    Route::resource('/capitals', 'CapitalController');


});
Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/chooses/create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="container">
        <h3 class="jumbotron"> Why ASCE</h3>
            <form method="POST" action="{{route('chooses.store')}}" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="exampleInputEmail1">English Header</label>
                    <input type="text" value="" name="header" class="form-control"placeholder="English header">
                    @error('header')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Arabic Header</label>
                    <input type="text" value="" name="header_ar" class="form-control"placeholder="Arabic Header">
                    @error('header_ar')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">French Header</label>
                    <input type="text" value="" name="header_fr" class="form-control"placeholder="French Header">
                    @error('header_fr')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label >English content</label>
                    <textarea name="content" class="form-control" id="" cols="30" rows="6"></textarea>
                    @error('content')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label >Arabic content</label>
                    <textarea name="content_ar" class="form-control" id="" cols="30" rows="6"></textarea>
                    @error('content_ar')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label >French content</label>
                    <textarea name="content_fr" class="form-control" id="" cols="30" rows="6"></textarea>
                    @error('content_fr')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>



            <button type="submit" class="btn btn-primary" style="margin-top:10px">Upload</button>
        </form>
    </div>


@endsection

resources/views/admin/chooses/edit.blade.php
@extends('admin.layouts.app')
@section('content')
<section class="content">
        <div class="row">
          <!-- left column -->
            <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                <h3 class="box-title">Quick Example</h3>
                </div>
              <!-- /.box-header -->
              <!-- form start -->
            <form  method="post" action="{{route('chooses.update' , $chooses->id )}}" class="form" enctype="multipart/form-data">
                  {{csrf_field()}}
                  <input type="hidden" name="_method" value="put">
                <div class="box-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">English Header</label>
                        <input type="text" value="{{$chooses->header}}" name="header" class="form-control"placeholder="English header">
                        @error('header')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Arabic Header</label>
                        <input type="text" value="{{$chooses->header_ar}}" name="header_ar" class="form-control"placeholder="Arabic Header">
                        @error('header_ar')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">French Header</label>
                        <input type="text" value="{{$chooses->header_fr}}" name="header_fr" class="form-control"placeholder="French Header">
                        @error('header_fr')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label >English content</label>
                        <textarea name="content" class="form-control" id="" cols="30" rows="6">{{$chooses->content}}</textarea>
                        @error('content')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label >Arabic content</label>
                        <textarea name="content_ar" class="form-control" id="" cols="30" rows="6">{{$chooses->content_ar}}</textarea>
                        @error('content_ar')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label >French content</label>
                        <textarea name="content_fr" class="form-control" id="" cols="30" rows="6">{{$chooses->content_fr}}</textarea>
                        @error('content_fr')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                  <button type="submit" class="btn btn-primary">Edit</button>
                </div>
            </form>
            </div>
            <!-- /.box -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </section>

@endsection

resources/views/admin/chooses/index.blade.php
@extends('admin.layouts.app')
@section('content')
<section class="content">
        <a href="{{ route('chooses.create') }}" class="btn btn-primary text-capitalize "> add new </a>
            <div class="row">
              <div class="col-md-12">
                <div class="box">
                  <div class="box-header with-border">
                    <h3 class="box-title">Why ASCE</h3>
                  </div>
                  <!-- /.box-header -->
                  <div class="box-body">
                    <table class="table table-bordered">
                      <tr>
                        <th style="width: 10px">#</th>
                        <th>English header</th>
                        <th>Arabic header</th>
                        <th>French header</th>
                        <th>English content </th>
                        <th>Arabic content </th>
                        <th>French content </th>
                        <th style="width: 100px">actions</th>
                      </tr>
                      @foreach ($chooses as $choose)
                            <tr>
                            <td>{{$choose->id}}</td>
                                <td> {{ $choose->header }} </td>
                                <td> {{ $choose->header_ar }} </td>
                                <td> {{ $choose->header_fr }} </td>
                                <td> {{ $choose->content }} </td>
                                <td> {{ $choose->content_ar }} </td>
                                <td> {{ $choose->content_fr }} </td>
                                <td>
                                    <form method="post" action="{{route('chooses.destroy', $choose->id)}}">
                                        <span>
                                            <a href="{{ route('chooses.edit', $choose->id) }}"><i class="fa fa-pencil btn btn-primary"> </i></a>
                                        </span>
                                            {{csrf_field()}}
                                            <input type="hidden" name="_method" value="DELETE" />
                                            <div class="btn-group">
                                                <button  onclick="return confirm(' هل انت متاكد ؟؟')" class="fa fa-trash btn btn-danger" type="submit"></button>
                                            </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach

                    </table>
                  </div>
                  <!-- /.box-body -->


              </div>

            </div>

          </section>
          <!-- /.content -->

@endsection