routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::group(['namespace' => 'Front' ,
             'prefix' =>'{locale}' ,
             'where' => ['locale' =>'[a-zA-Z]{2}'],

        ], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/about', 'HomeController@about');
    Route::get('/manufacturing', 'HomeController@manufacturing');
    Route::get('/contactUs', 'HomeController@contactUs');
    Route::get('/product', 'HomeController@product');
    Route::get('/service', 'HomeController@service');
    Route::get('/jobs', 'HomeController@job');
    Route::get('/register_form', 'HomeController@register');

    Auth::routes();

    Route::get('locale/{locale}', function ($locale){
        Session::put('locale', $locale);
        return redirect()->back();
    });

});
*/
Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/about', 'HomeController@about');
    Route::get('/manufacturing', 'HomeController@manufacturing');
    Route::get('/contactUs', 'HomeController@contactUs');
    Route::get('/product', 'HomeController@product');
    Route::get('/service', 'HomeController@service');
    Route::get('/jobs', 'HomeController@job');
    Route::get('/charts', 'HomeController@charts');
    Route::get('/capitals', 'HomeController@capital');

    Route::get('/register_form', 'HomeController@register');


    // Route::get('contact-us', 'ContactController@contactUs');
    // Route::post('contact-us', 'ContactController@contactUsPost')->name('contactus.store');

    Route::get('locale/{locale}', function ($locale){
        Session::put('locale', $locale);
        return redirect()->back();
    });

});
Auth::routes();
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index');
    Route::resource('/sliders', 'SliderController');
    Route::resource('/services', 'ServiceController');
    Route::resource('/portfolios', 'PortfolioController');
    Route::resource('/teams', 'TeamController');
    Route::resource('/testimonials', 'TestimonialController');
    Route::resource('/reports', 'ReportController');
    Route::resource('/abouts', 'AboutController');
    Route::resource('/statistics', 'StatisticController');
    Route::resource('/advisors', 'AdvisorController');
    Route::resource('/chooses', 'ChooseController');
    Route::resource('/products', 'ProductController');
    Route::resource('/manufacturing', 'ManufacturingController');
    Route::resource('/jobs', 'JobController');
    Route::resource('/charts', 'OrganizationChartController');
    Route::resource('/capitals', 'CapitalController');


});
Route::get('/home', 'HomeController@index')->name('home');

app/Models/About.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    protected $table = 'abouts';
    protected $fillable = ['title','title_ar','title_fr', 'content','content_ar','content_fr','image','number_expertise','description','description_ar','description_fr'];

    public function setImageAttribute($image)
    {
        $image = request()->file('image')->store('images');
        $this->attributes['image'] = $image;
    }
}

app/Http/Controllers/Admin/AboutController.php
<?php


namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\About;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $abouts = About::all();
        return view('admin.abouts.index',compact('abouts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.abouts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'image'                         => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'title'                         =>'required',
            'title_ar'                      =>'required',
            'title_fr'                      =>'required',
            'content'                       => 'required',
            'content_ar'                    => 'required',
            'content_fr'                    => 'required',
            'number_expertise'              => 'required',
            'description'                   => 'required',
            'description_ar'                => 'required',
            'description_fr'                => 'required',
        ]);
            $abouts = About::create($request->all());
            return Redirect('admin/abouts');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $abouts =About::find($id);
        return view('admin.abouts.edit',compact('abouts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'image'                         => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'title'                         =>'required',
            'title_ar'                      =>'required',
            'title_fr'                      =>'required',
            'content'                       => 'required',
            'content_ar'                    => 'required',
            'content_fr'                    => 'required',
            'number_expertise'              => 'required',
            'description'                   => 'required',
            'description_ar'                => 'required',
            'description_fr'                => 'required',
        ]);
        $abouts = About::find($id);
        $abouts->update($request->all());
        return Redirect('admin/abouts');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $abouts = About::find($id);
        $abouts->delete();
        return Redirect('admin/abouts');
    }
}

resources/views/admin/abouts/create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="container">
        <h3 class="jumbotron"> About Us</h3>
            <form method="POST" action="{{route('abouts.store')}}" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="input-group" >
                    <label>Image</label>
                    <input type="file" name="image" class="form-control">
                    @error('image')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror

                </div>
                <div class="form-group">
                    <label>English Title</label>
                    <input type="text" value="" name="title" class="form-control" placeholder="title">
                    @error('title')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Arabic Title</label>
                    <input type="text" value="" name="title_ar" class="form-control" placeholder="Arabic Title">
                    @error('title_ar')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>French Title</label>
                    <input type="text" value="" name="title_fr" class="form-control" placeholder="French Title">
                    @error('title_fr')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Number of expertise</label>
                    <input type="number" value="" name="number_expertise" class="form-control">
                    @error('number_expertise')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label >English Content</label>
                    <textarea name="content" class="form-control" id="" cols="30" rows="6"></textarea>
                    @error('content')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label >Arabic Content</label>
                    <textarea name="content_ar" class="form-control" id="" cols="30" rows="6"></textarea>
                    @error('content_ar')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label >French Content</label>
                    <textarea name="content_fr" class="form-control" id="" cols="30" rows="6"></textarea>
                    @error('content_fr')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>English Description </label>
                    <textarea name="description" class="form-control" id="" cols="30" rows="6"></textarea>
                    @error('description')
                        <div class="alert alert-danger">{{$message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Arabic Description </label>
                    <textarea name="description_ar" class="form-control" id="" cols="30" rows="6"></textarea>
                    @error('description_ar')
                        <div class="alert alert-danger">{{$message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label>French Description </label>
                    <textarea name="description_fr" class="form-control" id="" cols="30" rows="6"></textarea>
                    @error('description_fr')
                        <div class="alert alert-danger">{{$message }}</div>
                    @enderror
                </div>


            <button type="submit" class="btn btn-primary" style="margin-top:10px">Upload</button>
        </form>
    </div>


@endsection

resources/views/admin/abouts/edit.blade.php
@extends('admin.layouts.app')
@section('content')
<section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
              <div class="box-header with-border">
                <h3 class="box-title">Quick Example</h3>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
            <form  method="post" action="{{route('abouts.update' , $abouts->id )}}" class="form" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <input type="hidden" name="_method" value="put">
                <div class="box-body">
                    <div class="input-group control-group increment" >
                        <input type="file" name="image" class="form-control">
                        <img src = " {{asset('/' . $abouts->image )}}" height="200px" width="200px" >
                        @error('image')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>English Title</label>
                        <input type="text" value="{{$abouts->title}}" name="title" class="form-control" placeholder="title">
                        @error('title')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Arabic Title</label>
                        <input type="text" value="{{$abouts->title_ar}}" name="title_ar" class="form-control" placeholder="Arabic Title">
                        @error('title_ar')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>French Title</label>
                        <input type="text" value="{{$abouts->title_fr}}" name="title_fr" class="form-control" placeholder="French Title">
                        @error('title_fr')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Number of expertise</label>
                        <input type="number" value="{{$abouts->number_expertise}}" name="number_expertise" class="form-control" id="exampleInputEmail1" >
                        @error('number_expertise')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label >English Content</label>
                        <textarea name="content" class="form-control" id="" cols="30" rows="6">{{$abouts->content}}</textarea>
                        @error('content')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label >Arabic Content</label>
                        <textarea name="content_ar" class="form-control" id="" cols="30" rows="6">{{$abouts->content_ar}}</textarea>
                        @error('content_ar')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label >French Content</label>
                        <textarea name="content_fr" class="form-control" id="" cols="30" rows="6">{{$abouts->content_fr}}</textarea>
                        @error('content_fr')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>English Description </label>
                        <textarea name="description" class="form-control" id="" cols="30" rows="6">{{$abouts->description}}</textarea>
                        @error('description')
                            <div class="alert alert-danger">{{$message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Arabic Description </label>
                        <textarea name="description_ar" class="form-control" id="" cols="30" rows="6">{{$abouts->description_ar}}</textarea>
                        @error('description_ar')
                            <div class="alert alert-danger">{{$message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>French Description </label>
                        <textarea name="description_fr" class="form-control" id="" cols="30" rows="6">{{$abouts->description_fr}}</textarea>
                        @error('description_fr')
                            <div class="alert alert-danger">{{$message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Edit</button>
                </div>
            </form>
            </div>
            <!-- /.box -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </section>

@endsection

resources/views/admin/abouts/index.blade.php
@extends('admin.layouts.app')
@section('content')
<section class="content">
        <a href="{{ route('abouts.create') }}" class="btn btn-primary text-capitalize "> add new </a>
            <div class="row">
              <div class="col-md-12">
                <div class="box">
                  <div class="box-header with-border">
                    <h3 class="box-title">About US</h3>
                  </div>
                  <!-- /.box-header -->
                  <div class="box-body">
                    <table class="table table-bordered">
                      <tr>
                        <th style="width: 10px">#</th>
                        <th>Image</th>
                        <th>English Title</th>
                        <th>Arabic Title</th>
                        <th>Freach Title</th>
                        <th>English content </th>
                        <th>Arabic content </th>
                        <th>Freach content </th>
                        <th>English description </th>
                        <th>Arabic description </th>
                        <th>Freach description </th>
                        <th>number of expertise </th>
                        <th style="width: 100px">actions</th>
                      </tr>
                      @foreach ($abouts as $about)
                            <tr>
                            <td>{{$about->id}}</td>
                                <td> <img src="{{ asset('/'.$about->image) }}" height="100px" width="100px" alt="">
                                <td> {{ $about->title }}   </td>
                                <td> {{ $about->title_ar }}   </td>
                                <td> {{ $about->title_fr }}   </td>
                                <td> {{ $about->content }} </td>
                                <td> {{ $about->content_ar }} </td>
                                <td> {{ $about->content_fr }} </td>
                                <td> {{ $about->description }} </td>
                                <td> {{ $about->description_ar }} </td>
                                <td> {{ $about->description_fr }} </td>
                                <td> {{ $about->number_expertise }} </td>

                                <td>
                                    <form method="post" action="{{route('abouts.destroy', $about->id)}}">
                                        <span>
                                            <a href="{{ route('abouts.edit', $about->id) }}"><i class="fa fa-pencil btn btn-primary"> </i></a>
                                        </span>
                                            {{csrf_field()}}
                                            <input type="hidden" name="_method" value="DELETE" />
                                            <div class="btn-group">
                                                <button  onclick="return confirm(' هل انت متاكد ؟؟')" class="fa fa-trash btn btn-danger" type="submit"></button>
                                            </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach

                    </table>
                  </div>
                  <!-- /.box-body -->


              </div>

            </div>

          </section>
          <!-- /.content -->

@endsection