routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::group(['namespace' => 'Front' ,
             'prefix' =>'{locale}' ,
             'where' => ['locale' =>'[a-zA-Z]{2}'],

        ], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/about', 'HomeController@about');
    Route::get('/manufacturing', 'HomeController@manufacturing');
    Route::get('/contactUs', 'HomeController@contactUs');
    Route::get('/product', 'HomeController@product');
    Route::get('/service', 'HomeController@service');
    Route::get('/jobs', 'HomeController@job');
    Route::get('/register_form', 'HomeController@register');

    Auth::routes();

    Route::get('locale/{locale}', function ($locale){
        Session::put('locale', $locale);
        return redirect()->back();
    });

});
*/
Route::group(['namespace' => 'Front'], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/about', 'HomeController@about');
    Route::get('/manufacturing', 'HomeController@manufacturing');
    Route::get('/contactUs', 'HomeController@contactUs');
    Route::get('/product', 'HomeController@product');
    Route::get('/service', 'HomeController@service');
    Route::get('/jobs', 'HomeController@job');
    Route::get('/charts', 'HomeController@charts');
    Route::get('/capitals', 'HomeController@capital');

    Route::get('/register_form', 'HomeController@register');


    // Route::get('contact-us', 'ContactController@contactUs');
    // Route::post('contact-us', 'ContactController@contactUsPost')->name('contactus.store');

    Route::get('locale/{locale}', function ($locale){
        Session::put('locale', $locale);
        return redirect()->back();
    });

});
Auth::routes();
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index');
    Route::resource('/sliders', 'SliderController');
    Route::resource('/services', 'ServiceController');
    Route::resource('/portfolios', 'PortfolioController');
    Route::resource('/teams', 'TeamController');
    Route::resource('/testimonials', 'TestimonialController');
    Route::resource('/reports', 'ReportController');
    Route::resource('/abouts', 'AboutController');
    Route::resource('/statistics', 'StatisticController');
    Route::resource('/advisors', 'AdvisorController');
    Route::resource('/chooses', 'ChooseController');
    Route::resource('/products', 'ProductController');
    Route::resource('/manufacturing', 'ManufacturingController');
    Route::resource('/jobs', 'JobController');
    Route::resource('/charts', 'OrganizationChartController');
    Route::resource('/capitals', 'CapitalController');


});
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Manufacturing.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Manufacturing extends Model
{
    protected $table = 'manufacturing';
    protected $fillable = ['header', 'content','header_ar', 'content_ar','header_fr', 'content_fr'];

}

app/Http/Controllers/Admin/ManufacturingController.php
<?php


namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Manufacturing;

class ManufacturingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $manufacturing = Manufacturing::all();
        return view('admin.manufacturing.index',compact('manufacturing'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.manufacturing.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'header'                       =>'required',
            'content'                      => 'required',
            'header_ar'                    =>'required',
            'content_ar'                   => 'required',
            'header_fr'                    =>'required',
            'content_fr'                   => 'required',

        ]);
            $manufacturing = Manufacturing::create($request->all());
            return Redirect('admin/manufacturing');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $manufacturing =Manufacturing::find($id);
        return view('admin.manufacturing.edit',compact('manufacturing'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'header'                       =>'required',
            'content'                      => 'required',
            'header_ar'                    =>'required',
            'content_ar'                   => 'required',
            'header_fr'                    =>'required',
            'content_fr'                   => 'required',

        ]);
        $manufacturing = Manufacturing::find($id);
        $manufacturing->update($request->all());
        return Redirect('admin/manufacturing');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $manufacturing = Manufacturing::find($id);
        $manufacturing->delete();
        return Redirect('admin/manufacturing');
    }
}

resources/views/admin/manufacturing/create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="container">
        <h3 class="jumbotron"> Manufacturing </h3>
        <form method="POST" action="{{route('manufacturing.store')}}" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="form-group">
                <label>English Header</label>
                <input type="text" value="" name="header" class="form-control" placeholder="English header">
                @error('header')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label>Arabic Header</label>
                <input type="text" value="" name="header_ar" class="form-control" placeholder="Arabic header">
                @error('header_ar')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label>French Header</label>
                <input type="text" value="" name="header_fr" class="form-control" placeholder="French header">
                @error('header_fr')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label >English content</label>
                <textarea name="content" class="form-control" id="" cols="30" rows="6"></textarea>
                @error('content')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label >Arabic content</label>
                <textarea name="content_ar" class="form-control" id="" cols="30" rows="6"></textarea>
                @error('content_ar')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label >French content</label>
                <textarea name="content_fr" class="form-control" id="" cols="30" rows="6"></textarea>
                @error('content_fr')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary" style="margin-top:10px">Upload</button>
        </form>
    </div>


@endsection

resources/views/admin/manufacturing/edit.blade.php
@extends('admin.layouts.app')
@section('content')
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
        <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                <h3 class="box-title">Quick Example</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form  method="post" action="{{route('manufacturing.update' , $manufacturing->id )}}" class="form" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <input type="hidden" name="_method" value="put">
                    <div class="box-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">English Header</label>
                        <input type="text" value="{{$manufacturing->header}}" name="header" class="form-control" >
                        @error('header')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Arabic Header</label>
                        <input type="text" value="{{$manufacturing->header_ar}}" name="header_ar" class="form-control" >
                        @error('header_ar')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">French Header</label>
                        <input type="text" value="{{$manufacturing->header_fr}}" name="header_fr" class="form-control" >
                        @error('header_fr')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">English content</label>
                        <textarea name="content"  class="form-control" id="" cols="30" rows="10">{{$manufacturing->content}}</textarea>
                        @error('content')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Arabic content</label>
                        <textarea name="content_ar"  class="form-control" id="" cols="30" rows="10">{{$manufacturing->content_ar}}</textarea>
                        @error('content_ar')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">French content</label>
                        <textarea name="content_fr"  class="form-control" id="" cols="30" rows="10">{{$manufacturing->content_fr}}</textarea>
                        @error('content_fr')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Edit</button>
                </div>
                </form>
            </div>
            <!-- /.box -->
        </div>
        <!--/.col (right) -->
    </div>
    <!-- /.row -->
</section>

@endsection

resources/views/admin/manufacturing/index.blade.php
@extends('admin.layouts.app')
@section('content')
<section class="content">
    <a href="{{ route('manufacturing.create') }}" class="btn btn-primary text-capitalize "> add new </a>
        <div class="row">
            <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                <h3 class="box-title"> Manufacturing </h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                <table class="table table-bordered">
                    <tr>
                    <th style="width: 10px">#</th>
                    <th>English header</th>
                    <th>Arabic header</th>
                    <th>French header</th>
                    <th>English content </th>
                    <th>Arabic content </th>
                    <th>French content </th>
                    <th style="width: 100px">actions</th>
                    </tr>
                    @foreach ($manufacturing as $manufact)
                        <tr>
                        <td>{{$manufact->id}}</td>
                            <td> {{ $manufact->header }}   </td>
                            <td> {{ $manufact->header_ar }}   </td>
                            <td> {{ $manufact->header_fr }}   </td>
                            <td> {{ $manufact->content }} </td>
                            <td> {{ $manufact->content_ar }} </td>
                            <td> {{ $manufact->content_fr }} </td>
                            <td>
                                <form method="post" action="{{route('manufacturing.destroy', $manufact->id)}}">
                                    <span>
                                        <a href="{{ route('manufacturing.edit', $manufact->id) }}"><i class="fa fa-pencil btn btn-primary"> </i></a>
                                    </span>
                                        {{csrf_field()}}
                                        <input type="hidden" name="_method" value="DELETE" />
                                        <div class="btn-group">
                                            <button  onclick="return confirm(' هل انت متاكد ؟؟')" class="fa fa-trash btn btn-danger" type="submit"></button>
                                        </div>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
            <!-- /.box-body -->


        </div>

    </div>

</section>
<!-- /.content -->


@endsection